// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YuruChara.Infrastructure;

#nullable disable

namespace YuruChara.Infrastructure.Migrations
{
    [DbContext(typeof(YuruCharaDbContext))]
    [Migration("20260919135412_AddLicenseTermsUrl")]
    partial class AddLicenseTermsUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YuruChara.Domain.Mascots.Mascot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DebutYear")
                        .HasColumnType("integer");

                    b.Property<string>("ImageLicenseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LicenseTermsUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Motif")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NameJa")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameRomaji")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("OwningBody")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PrefectureId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCitations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VerificationLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DebutYear");

                    b.HasIndex("Motif");

                    b.HasIndex("PrefectureId");

                    b.ToTable("mascots", (string)null);
                });

            modelBuilder.Entity("YuruChara.Domain.Prefectures.Prefecture", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)");

                    b.Property<Point>("Centroid")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Point>("LabelPoint")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NameJa")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NameRomaji")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_prefectures_boundary_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.ToTable("prefectures", (string)null);
                });

            modelBuilder.Entity("YuruChara.Domain.Mascots.Mascot", b =>
                {
                    b.HasOne("YuruChara.Domain.Prefectures.Prefecture", "Prefecture")
                        .WithMany("Mascots")
                        .HasForeignKey("PrefectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prefecture");
                });

            modelBuilder.Entity("YuruChara.Domain.Prefectures.Prefecture", b =>
                {
                    b.Navigation("Mascots");
                });
#pragma warning restore 612, 618
        }
    }
}
